# Generated by Django 4.0.1 on 2022-06-07 18:30

import academic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(error_messages={'unique': 'Ya existe esta carrera.'}, max_length=255, unique=True, validators=[academic.validators.name_validator], verbose_name='career')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
        ),
    ]
