# Generated by Django 4.0.1 on 2022-06-07 01:37

import academic.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipality', '0001_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_id', models.CharField(default='0001', max_length=4, validators=[academic.validators.number_validator], verbose_name='id locality')),
                ('locality_name', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='locality')),
                ('municipality', models.ForeignKey(default='053', on_delete=django.db.models.deletion.CASCADE, to='municipality.municipality')),
                ('state', models.ForeignKey(default='16', on_delete=django.db.models.deletion.CASCADE, to='state.state')),
            ],
        ),
    ]
