# Generated by Django 4.0.1 on 2022-06-06 00:30

import academic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='school name')),
                ('catchword', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='catchword')),
                ('logo', models.ImageField(help_text='Obligatoria. Logo de la escuela.', upload_to='assets/school/%Y/%m/%d', verbose_name='school logo')),
                ('level', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='level')),
                ('control', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='control')),
                ('clue', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='clue')),
                ('sustenance', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='sustenance')),
                ('location', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='location')),
                ('municipality', models.CharField(max_length=255, validators=[academic.validators.name_validator], verbose_name='municipality')),
                ('student_population', models.PositiveIntegerField(verbose_name='student population')),
                ('teaching_population', models.PositiveIntegerField(verbose_name='teaching population')),
            ],
        ),
    ]
