# Generated by Django 4.0.1 on 2022-06-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('cve_proc', models.CharField(default='000000', error_messages={'unique': 'Ya existe una escuela con esa clave.'}, max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Clave')),
                ('nom_proc', models.CharField(blank=True, max_length=130, null=True, verbose_name='Nombre completo de la institución donde concluyó el nivel medio superior')),
                ('ciu_proc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad donde se ubica la institución')),
                ('reg_proc', models.CharField(choices=[('1', 'Público'), ('2', 'Privado'), ('3', 'Federal por cooperación')], default='1', max_length=1, verbose_name='Régimen de sostenimiento')),
                ('mod_bac', models.CharField(choices=[('1', 'Bachillerato general'), ('2', 'Bachillerato tecnológico'), ('3', 'Profesional técnico bachiller'), ('4', 'Bachillerato intercultural (bilingüe indígena)'), ('5', 'Bachillerato internacional'), ('6', 'Acuerdo secretarial 286 Bachillerato'), ('7', 'Preparatoria abierta'), ('8', 'Educación media superior a distancia')], default='1', max_length=1, verbose_name='modalidad')),
            ],
        ),
    ]
