from django.forms import models

from students.models import Student


class StudentForm(models.ModelForm):
    class Meta:
        model = Student

        fields = '__all__'

        labels = {
            'tipo_exa': 'Tipo de examen',
            'apli': 'Número de aplicación',
            'fecha_apli': 'Fecha de aplicación',
            'cve_inst': 'Clave de la institución en donde se llevó a cabo la aplicación',
            'identifica': 'Identificación de la aplicación',
            'folio': 'Folio',
            'matricula': 'Clave o matrícula de la institución',
            'nombre': 'Nombre(s)',
            'ape_pat': 'Apellido paterno',
            'ape_mat': 'Completo',
            'completo': 'Apellido materno',
            'dia_nac': 'Día de nacimiento',
            'mes_nac': 'Mes de nacimiento',
            'ano_nac': 'Año de nacimiento',
            'sexo': 'Sexo',
            'enti_nac': '¿en qué entidad nació?',
            'imp_cam': 'Enfrenta dificultad para caminar',
            'imp_ecu': 'Enfrenta dificultad  para escuchar, aun a corta distancia',
            'imp_ver': 'Enfrenta problemas graves para ver, aun con lentes',
            'imp_pan': 'Enfrenta problemas de ansiedad',
            'imp_pca': 'Problemas para controlar mi agresividad',
            'imp_pdp': 'Enfrenta problemas de depresión',
            'imp_pat': 'Enfrenta problemas de atención',
            'dis_sor': 'Discapacidad de sordera',
            'dis_ceg': 'Discapacidad de ceguera',
            'dis_pps': 'Discapacidad de problemas psicomotrices',
            'apo_aml': 'Apoyo para aplicador con manejo de lenguaje de señas',
            'apo_lcu': 'Apoyo para lector de cuadernillo',
            'apo_llh': 'Apoyo para el llenado de la hoja de respuestas',
            'li_mad': 'Madre',
            'li_pad': 'Padre',
            'edo_proc': '¿dónde concluyó el nivel medio superior?',
            'nom_proc': 'Nombre completo de la institución donde concluyó el nivel medio superior',
            'ciu_proc': 'Nombre de la ciudad donde se ubica la institución en la que concluyó el nivel medio '
                        'superior; si fue en el extranjero indique el país.',
            'cve_proc': 'Clave de la institución en la que concluyó sus estudios de bachillerato',
            'ano_bac': '¿en qué año concluyó el nivel medio superior?',
            'reg_proc': '¿cuál es el régimen de sostenimiento de la escuela en la que estudió el último año del nivel '
                        'medio superior?',
            'mod_bac': '¿en qué modalidad obtuvo su certificado del bachillerato?',
            'turno': '¿en qué turno estudió el último año del nivel medio superior?',
            'prom_bac': 'Anote su promedio final del nivel medio superior en los cuadros y rellene los óvalos '
                        'correspondientes.',
            'bec_dac': 'Por alto desempeño académico',
            'bec_nec': 'Por necesidad económica',
            'bec_hda': 'Por habilidad deportiva o artística',
            'exa_ext': '¿cuántos exámenes extraordinarios presentó en el nivel medio superior?',
            'mat_rep': '¿cuántas materias reprobó en el nivel medio superior?',
            'fal_esc': 'Faltar a la escuela',
            'noe_cla': 'No entrar a clases estando en la escuela',
            'pre_exa': 'Presentar un examen sin haber estudiado todos los temas',
            'noe_tar': 'No entregar una tarea',
            'dan_malf': 'Golpearan, patearan, cachetearan o maltrataran físicamente?',
            'dan_ofi': 'Ofendieran con insultos, groserías o apodos hirientes?',
            'dan_eir': 'Excluyeran, ignoraran o rechazaran?',
            'dan_reqc': 'Robaran, escondieran o quitaran sus cosas?',
            'dan_mft': 'Molestaran por medio de facebook, twitter, correo electrónico o mensajes de'
                       'texto por el celular?',
            'dan_fhc': 'Forzaran a hacer cosas que no quería?',
            'est_alca': '¿cuál es el nivel máximo de estudios que le gustaría alcanzar?',
            'no_uni': 'Si no se graduara de una carrera universitaria,'
                      '¿qué ingreso mensual promedio esperaría obtener dentro de 10 años?',
            'si_uni': 'Si se graduara de una carrera universitaria,'
                      '¿qué ingreso mensual promedio esperaría obtener dentro de 10 años?',
            'si_posg': 'Si se graduara de un posgrado, '
                       '¿qué ingreso mensual promedio esperaría obtener dentro de 10 años?',
            'ing_int': 'Información en internet',
            'ing_lib': 'Libros de esparcimiento',
            'ing_can': 'Letra de canciones',
            'hab_ptex': 'Habilidad en la computadora para crear y editar un documento'
                        'utilizando un procesador de texto',
            'hab_pres': 'Habilidad para utilizar programas para hacer presentaciones',
            'hab_fbas': 'Habilidad para emplear funciones básicas en hojas de cálculo (captura de datos, formato, '
                        'ordenamiento y uso de fórmulas)',
            'hab_baj': 'Habilidad para bajar programas y archivos de internet',
            'fre_ppa': 'Participo en la planeación de actividades',
            'fre_cde': 'Colaboro en el desarrollo de estrategias para cumplir con las metas',
            'fre_tsc': 'Intervengo para tratar de solucionar conflictos',
            'fre_sme': 'Hago sugerencias para mejorar la ejecución del equipo',
            'fre_acp': 'Ayudo a mis compañeros a resolver problemas',
            'fre_act': 'Apoyo a mis compañeros cuando tienen mucho trabajo',
            'act_prio': 'Establezco prioridades para determinar el orden en el que debo realizar mis actividades',
            'act_flim': 'Me impongo fechas límite para terminar trabajos importantes',
            'act_pri': 'Termino primero las tareas más importantes antes de empezar con otras tareas',
            'act_gpa': 'Me gusta planear mis actividades importantes con anticipación',
            'fre_eje': '¿con qué frecuencia realiza ejercicio?',
            'int_eje': '¿qué tan intenso es el ejercicio que realiza?',
            'ses_eje': 'Aproximadamente, ¿cuánto duran las sesiones de ejercicio que realiza?',
            'ori_aue': 'Autoestima',
            'ori_cme': 'Control de miedos',
            'ori_esx': 'Educación sexual',
            'ori_hso': 'Habilidades sociales',
            'ori_mdp': 'Manejo de depresión',
            'ori_mes': 'Manejo de estrés',
            'ori_mag': 'Manejo de la agresividad',
            'ori_nut': 'Nutrición',
            'hrs_trab': '¿cuántas horas a la semana dedicó a trabajar durante el nivel medio superior? (considere que '
                        'su trabajo puede ser asalariado o sin pago, por ejemplo trabajar en un negocio familiar).',
            'niv_soc': '¿cuál considera que es el nivel socioeconómico de su familia?',
            'esco_mad': '¿cuál es el máximo nivel de estudios de su madre (aunque haya fallecido)?',
            'esco_pad': '¿cuál es el máximo nivel de estudios de su padre (aunque haya fallecido)?',
            'cuan_lib': '¿cuántos libros hay en su casa? (no considere revistas, periódicos o libros de texto)',
            'ser_tele': 'Línea telefónica',
            'ser_lav': 'Lavadora de ropa',
            'ser_ref': 'Refrigerador',
            'ser_hor': 'Horno de microondas',
            'ser_inte': 'Internet',
            'ser_cabl': 'Televisión de paga (cablevisión, sky, etc.)',
            'ser_tabl': 'Tableta (ipad, samsung galaxy, etc.)',
            'bien_pc': 'Computadora',
            'ser_tv': 'Televisor',
            'ser_auto': 'Automóvil',
            'ser_bano': 'Baños completos',
            'vac_rm': '¿cuántas veces ha salido de vacaciones dentro de la república mexicana en los últimos 2 años?',
            'con_exao': '¿cuántas veces ha contestado exámenes de opción múltiple en los que rellena círculos ('
                        'alveolos) en este año escolar?',
            'cur_esc': 'En su escuela',
            'cur_ipa': 'En una institución particular',
            'cur_mpa': 'Con un maestro particular',
            'pre_exa2': '¿cuántas veces ha presentado el examen nacional de ingreso a la educación'
                        'superior (exani-ii)?',
            'pos_sus': 'Posición alcanzada por el sustentante en el examen de admisión',
            'icne': 'Calificación  en índice ceneval del examen de admisión',
            'percen': 'Percentil del examen de admisión',
            'porcecne': '% > cne del examen de admisión',
            'pcne': 'Calificación en porcentaje de aciertos del examen de admisión',
            'ppma': 'Calificación de pensamiento matemático en porcentaje de aciertos',
            'ppan': 'Calificación de pensamiento analítico en porcentaje de aciertos',
            'pele': 'Calificación de estructura de la lengua en porcentaje de aciertos',
            'pcle': 'Calificación de comprensión lectora en porcentaje de aciertos',
            'ipma': 'Calificación de pensamiento matemático en índice ceneval',
            'ipan': 'Calificación de pensamiento analítico en índice ceneval',
            'iele': 'Calificación de estructura de la lengua en índice ceneval',
            'icle': 'Calificación de comprensión lectora en índice ceneval',
            'ddd_mg_mat': 'Dictamen de matemáticas "diagnóstico"',
            'ddd_mg_fis': 'Dictamen de física',
            'ddd_mg_les': 'Dictamen de lenguaje escrito',
            'ddd_mg_ing': 'Dictamen de inglés',
        }
