# Generated by Django 4.0.1 on 2022-06-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=9, verbose_name='id number')),
                ('student_name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('paternal_surname', models.CharField(max_length=255, null=True, verbose_name='paternal surname')),
                ('maternal_surname', models.CharField(max_length=255, null=True, verbose_name='maternal surname')),
                ('option', models.PositiveSmallIntegerField(choices=[(1, 'Tesis'), (2, 'EGEL'), (3, 'Proyecto de investigación'), (4, 'Dual')], verbose_name='option')),
                ('egress_period', models.PositiveSmallIntegerField(choices=[('1', 'Enero-Junio'), ('2', 'Agosto-Diciembre')], verbose_name='egress period')),
                ('egress_year', models.DateField(default=2022, verbose_name='egress_year')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career')),
            ],
        ),
    ]
