# Generated by Django 4.0.1 on 2022-06-06 00:30

import academic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255, unique=True, validators=[academic.validators.name_validator], verbose_name='department name')),
            ],
        ),
    ]
